In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [31]:
without_pca = pd.read_csv("../results_without_pca.csv")
with_pca = pd.read_csv("../results_with_pca.csv")

without_pca["Approach"] = "Without PCA"
with_pca["Approach"] = "With PCA"

comparison_df = pd.concat(
    [without_pca, with_pca],
    ignore_index=True
)

In [32]:
comparison_df

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,RMSE Gap,Train R²,Test R²,R² Gap,Approach
0,Linear Regression,11005.554857,12409.074670,15107.033789,16953.106502,1846.072712,0.935074,0.907589,0.027485,Without PCA
1,Random Forest,5590.180258,13205.709747,8751.939276,18269.396237,9517.456961,0.978209,0.892681,0.085528,Without PCA
2,ElasticNet,12555.910623,13680.906099,17096.599737,18977.918407,1881.318670,0.916846,0.884196,0.032650,Without PCA
3,Ridge,12573.735862,13773.605079,17050.979564,19048.341465,1997.361901,0.917289,0.883335,0.033955,Without PCA
4,Lasso,12608.593424,13839.625415,17069.062880,19094.083836,2025.020956,0.917114,0.882774,0.034340,Without PCA
5,Gradient Boosting,6334.375601,14115.623409,8347.422368,20350.536686,12003.114317,0.980177,0.866838,0.113339,Without PCA
6,HistGradientBoosting,6344.884059,14022.391238,8614.092598,20353.364864,11739.272266,0.978890,0.866801,0.112089,Without PCA
7,AdaBoost,15681.380190,17145.964950,19843.200950,22275.405093,2432.204143,0.887982,0.840457,0.047526,Without PCA
8,KNN,0.000000,16304.958099,0.000000,23850.262038,23850.262038,1.000000,0.817100,0.182900,Without PCA
9,Decision Tree,9728.996468,18454.968677,13665.391536,25408.595560,11743.204024,0.946874,0.792418,0.154455,Without PCA
10,ElasticNet,12555.910623,13680.906099,17096.599737,18977.918407,1881.318670,0.916846,0.884196,0.032650,With PCA
11,Ridge,12573.735862,13773.605079,17050.979564,19048.341465,1997.361901,0.917289,0.883335,0.033955,With PCA
12,Lasso,12608.593424,13839.625415,17069.062880,19094.083836,2025.020956,0.917114,0.882774,0.034340,With PCA
13,Gradient Boosting,6334.375601,14113.916655,8347.422368,20352.880260,12005.457892,0.980177,0.866808,0.113369,With PCA
14,HistGradientBoosting,6344.884059,14022.391238,8614.092598,20353.364864,11739.272266,0.978890,0.866801,0.112089,With PCA

In [33]:
print("WITHOUT PCA")
display(without_pca)

print("WITH PCA")
display(with_pca)

WITHOUT PCA

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,RMSE Gap,Train R²,Test R²,R² Gap,Approach
0,Linear Regression,11005.554857,12409.074670,15107.033789,16953.106502,1846.072712,0.935074,0.907589,0.027485,Without PCA
1,Random Forest,5590.180258,13205.709747,8751.939276,18269.396237,9517.456961,0.978209,0.892681,0.085528,Without PCA
2,ElasticNet,12555.910623,13680.906099,17096.599737,18977.918407,1881.318670,0.916846,0.884196,0.032650,Without PCA
3,Ridge,12573.735862,13773.605079,17050.979564,19048.341465,1997.361901,0.917289,0.883335,0.033955,Without PCA
4,Lasso,12608.593424,13839.625415,17069.062880,19094.083836,2025.020956,0.917114,0.882774,0.034340,Without PCA
5,Gradient Boosting,6334.375601,14115.623409,8347.422368,20350.536686,12003.114317,0.980177,0.866838,0.113339,Without PCA
6,HistGradientBoosting,6344.884059,14022.391238,8614.092598,20353.364864,11739.272266,0.978890,0.866801,0.112089,Without PCA
7,AdaBoost,15681.380190,17145.964950,19843.200950,22275.405093,2432.204143,0.887982,0.840457,0.047526,Without PCA
8,KNN,0.000000,16304.958099,0.000000,23850.262038,23850.262038,1.000000,0.817100,0.182900,Without PCA
9,Decision Tree,9728.996468,18454.968677,13665.391536,25408.595560,11743.204024,0.946874,0.792418,0.154455,Without PCA

WITH PCA

,Model,Train MAE,Test MAE,Train RMSE,Test RMSE,RMSE Gap,Train R²,Test R²,R² Gap,Approach
0,ElasticNet,12555.910623,13680.906099,17096.599737,18977.918407,1881.318670,0.916846,0.884196,0.032650,With PCA
1,Ridge,12573.735862,13773.605079,17050.979564,19048.341465,1997.361901,0.917289,0.883335,0.033955,With PCA
2,Lasso,12608.593424,13839.625415,17069.062880,19094.083836,2025.020956,0.917114,0.882774,0.034340,With PCA
3,Gradient Boosting,6334.375601,14113.916655,8347.422368,20352.880260,12005.457892,0.980177,0.866808,0.113369,With PCA
4,HistGradientBoosting,6344.884059,14022.391238,8614.092598,20353.364864,11739.272266,0.978890,0.866801,0.112089,With PCA